<?php

    function dna_sequencer($input){
        $output = '';

        for ($i = 0; $i < strlen($input); $i++){
            switch ($input[$i]) {
                case 'A':
                    $output .= 'T';
                    break;
                case 'T':
                    $output .= 'A';
                    break;
                case 'C':
                    $output .= 'G';
                    break;
                case 'G':
                    $output .= 'C';
                    break;
                default:
                    $output = '';
            }
        }
        return $output;
    }
